app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::get('contact', 'ContactController@index');

Route::get('hello/{name?}', 'ContactController@hello');

// Provide controller methods with object instead of ID

Route::model('projects', 'Project');
Route::bind('projects', function($value, $route) {
	return App\Project::whereSlug($value)->first();
});
Route::resource('projects', 'ProjectsController'); //

Route::model('tasks', 'Task');
Route::bind('tasks', function($value, $route) {
	return App\Task::whereSlug($value)->first();
});
Route::resource('projects.tasks', 'TasksController');


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Project.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model {

	protected $guarded = [];
	
	public function tasks()
	{
		return $this->hasMany('App\Task');
	}

}

app/Http/Controllers/ProjectsController.php
<?php namespace App\Http\Controllers;

use App\Project;
use App\Http\Requests;
use App\Http\Controllers\Controller;
 
use Illuminate\Http\Request;
use Input;
use Redirect;

class ProjectsController extends Controller {

	protected $rules = [
		'name' => ['required', 'min:3'],
		'slug' => ['required'],
	];
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$projects = Project::all();
		
		return view('projects.index', compact('projects'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('projects.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, $this->rules);
 
		$input = Input::all();
		Project::create($input);

		return Redirect::route('projects.index')->with('message','Project created');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show(Project $project)
	{
		return view('projects.show',compact('project'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit(Project $project)
	{
		return view('projects.edit',compact('project'));	
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Project $project,Request $request)
	{
		$this->validate($request, $this->rules);
 
		$input = array_except(Input::all(), '_method');
		$project->update($input);
 
		return Redirect::route('projects.show', $project->slug)->with('message', 'Project updated.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy(Project $project)
	{
		$project->delete();
 
		return Redirect::route('projects.index')->with('message', 'Project deleted.');
	}
}

resources/views/projects/create.blade.php
<!-- /resources/views/projects/create.blade.php -->
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Create Project</div>

				<div class="panel-body">
				 	{!! Form::model(new App\Project, ['route' => ['projects.store']]) !!}
        				@include('projects/partials/_form', ['submit_text' => 'Create Project'])
    				{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/projects/edit.blade.php
<!-- /resources/views/projects/edit.blade.php -->
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Edit Project</div>

				<div class="panel-body">
				 	{!! Form::model($project, ['method' => 'PATCH', 'route' => ['projects.update', $project->slug]]) !!}
        				@include('projects/partials/_form', ['submit_text' => 'Edit Project'])
    				{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/projects/index.blade.php
<!-- /resources/views/projects/index.blade.php -->

 @extends('app')

@section('content')
{{ ddd($projects) }}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Projects</div>

                <div class="panel-body">
                    @if ( !$projects->count() )
                        You have no projects
                    @else
                        <ul>
                            @foreach( $projects as $project )
                                <li>
                                    {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('projects.destroy', $project->slug))) !!}
                                        <a href="{{ route('projects.show', $project->slug) }}">{{ $project->name }}</a>
                                        (
                                            {!! link_to_route('projects.edit', 'Edit', array($project->slug), array('class' => 'btn btn-info')) !!},
                                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                                        )
                                    {!! Form::close() !!}
                                </li>
                            @endforeach
                        </ul>
                    @endif
                 
                    <p>
                        {!! link_to_route('projects.create', 'Create Project') !!}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/show.blade.php
<!-- /resources/views/projects/show.blade.php -->
@extends('app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $project->name }}</div>

                <div class="panel-body">
                   @if ( !$project->tasks->count() )
        Your project has no tasks.
    @else
        <ul>
            @foreach( $project->tasks as $task )
                <li>
                    {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('projects.tasks.destroy', $project->slug, $task->slug))) !!}
                        <a href="{{ route('projects.tasks.show', [$project->slug, $task->slug]) }}">{{ $task->name }}</a>
                        (
                            {!! link_to_route('projects.tasks.edit', 'Edit', array($project->slug, $task->slug), array('class' => 'btn btn-info')) !!},
 
                            {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                        )
                    {!! Form::close() !!}
                </li>
            @endforeach
        </ul>
    @endif
 
    <p>
        {!! link_to_route('projects.index', 'Back to Projects') !!} |
        {!! link_to_route('projects.tasks.create', 'Create Task', $project->slug) !!}
    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection